# Generated by Django 4.2.23 on 2025-09-16 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0214_alter_contest_authors_alter_contest_curators_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='judge',
            name='is_lib',
            field=models.BooleanField(default=False, verbose_name='library judge'),
        ),
    ]
