# Generated by Django 4.2.23 on 2025-10-26 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0215_judge_is_lib'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judge',
            name='is_lib',
            field=models.BooleanField(default=True, verbose_name='library judge'),
        ),
    ]
