# Generated by Django 4.2.23 on 2025-10-28 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0216_alter_judge_is_lib'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='is_kt',
            field=models.BooleanField(default=False, verbose_name='KT contest'),
        ),
    ]
