# Generated by Django 4.2.27 on 2026-01-07 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0217_contest_is_kt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='is_kt',
            field=models.BooleanField(default=False, verbose_name='Kiem tra'),
        ),
    ]
