# Generated by Django 4.2.27 on 2026-01-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0218_alter_contest_is_kt'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sessionID',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
